app.controller('HomeController', ['$scope', function($scope) {
    function age() {
        var birthdate = new Date("1992/5/1");
        var cur = new Date();
        var diff = cur-birthdate;
        var age = Math.floor(diff/31536000000);
        return age;
    };
    
    var myAge = age();
    $scope.myname = "Gabriel Pi&ntilde;ango";
    $scope.home = {
        homeEng: {
            title: "Resume",
            content: "My name is <b>Gabriel Pi&ntilde;ango</b>, I'm a "+ myAge + " years old venezuelan guy living in Santiago de Chile, CHile. Fom an early age I have been deeply interested in technology, said interest is what led me to pursuit a career in <b>Information Engineering</b>.<p></p><p> In 2010 I started to study in Universidad Tecnologica del Centro, located in Guacara, Venezuela, in order to obtain a degree in the aforementioned career. During my studies I got to establish a projection about what professional profile I wanted to achieve, likewise I took the initiative to learn Front-End technologies like <i>HTML5</i>, <i>CSS3</i> and <i>JavaScript</i>. Throughout Octuber of 2015 I decided to work by myself to get more experience as a Web Developer, this way I got to build my first project: <a href='http://www.areiro.com' target='_blank'><i>Areiro.com</i></a>.  New projects came along 2015, with which I could put my knowledge into practice and learn new things, such as: Zurb Foundation and AngularJS; I used the latter to build this website.</p>Currently I am expanding my knowledge in this area so I could be able to build and implement RESTful APIs.<p>Moreover, I consider myself a Linux follower, I started to use it in 2009 and it was during 2010 that I decided to use it as my computers' main OS.</p>",
            metaContent: "My name is Gabriel Piñango, I'm a "+ myAge + " years old guy living in Maracay, Venezuela. Fom an early age I have been deeply interested in technology, said interest is what led me to pursuit a career in <b>Information Engineering. In 2010 I started to study in Universidad Tecnologica del Centro, located in Guacara, Venezuela, in order to obtain a degree in the aforementioned career. During my studies I got to establish a projection about what professional profile I wanted to achieve, likewise I took the initiative to learn Front-End technologies like HTML5, CSS3 and JavaScript. Throughout Octuber of 2015 I decided to work by myself to get more experience as a Web Developer, this way I got to build my first project: Areiro.com.  New projects came along 2015, with which I could put my knowledge into practice and learn new things, such as: Zurb Foundation and AngularJS; I used the latter to build this website.Currently I am expanding my knowledge in this area so I could be able to build and implement RESTful APIs.Moreover, I consider myself a Linux follower, I started to use it in 2009 and it was during 2010 that I decided to use it as my computers' main OS."
        },
        homeSpa: {
            title: "Resumen",
            content: "Mi nombre es <b>Gabriel Pi&ntilde;ango</b>, actualmente tengo "+ myAge +"  a&ntilde;os de edad y me encuentro en la Santiago de Chile, Chile. Desde temprana edad he sentido interes por la tecnologia, dicho interes me condujo a perseguir un titulo en <b>Ingenieria en Informacion</b>.<p></p><p>En el año 2010 comence mis estudios en la Universidad Tecnologica del Centro, ubicada en Guacara Edo. Carabobo, Venezuela, con el objetivo de obtener un titulo en Ingenieria en Informacion. Durante mis estudios logre establecer una proyeccion del perfil profesional que deseaba.</p> <div class='hide-for-small-only'><p>En el año 2015 fije como meta aprender Ruby y Ruby on Rails, para comenzar a formar mi perfil profesional, asi mismo decidi apredender herramientas front-end como <i>HTML5</i>, <i>CSS3</i> y <i>JavaScript</i>. Durante Ocutubre del 2015 decidi comenzar a trabajar como freelancer, para lograr obtener mayor experiencia en el area de desarrollo web, de esta manera logre desarrollar mi primer proyecto: <a href='http://www.areiro.com' target='_blank'>Areiro.com</a>. En el transcurso del a&ntilde;o, nuevos proyectos llegaron, con los cuales pude conocer y poner en practica nuevas herramientas, entre ellas: Zurb Foundation, framework de HTML5 desarrollado por ZURB y AngularJS, con el cual esta pagina esta construida.</p> <p>Actualmente me encuentro expandiendo mis conocimientos en las herramientas antes menciondas, para desarrollar e implementar Restful API.</p> Asi mismo, me considero un seguidor de Linux, comence a usarlo en el a&ntilde;o 2009 y fue durante el a&ntilde;o 2010 que decidi utilizarlo como el SO principal en mis computadoras, actualmente tengo instalada la distribucion Ubuntu, pero disfruto probar otras distribuciones.</div>"
        }
    };
}]);